# Conexion a la base de datos
default: &default
  adapter: sqlserver
  username: sa
  password: GrupoPeliculizate#0112
  host: 172.22.15.132
  database: peliculizate_DB     

development:
  <<: *default
  database: peliculizate_Dev

test:
  <<: *default
  database: peliculizate_Test

production:
  <<: *default
  database: peliculizate_Prod
