default: &default
  adapter: sqlserver
  username: db_aaf452_peliswatch_admin
  password: "teamoariel0112"
  host: SQL9001.site4now.net
  database: db_aaf452_peliswatch
  encoding: utf8

development:
  <<: *default
  database: db_aaf452_peliswatch

test:
  <<: *default
  database: db_aaf452_peliswatch

production:
  <<: *default
  database: db_aaf452_peliswatch
