default: &default
  adapter: sqlserver
  username: sa
  password: "GrupoPeliculizate#0112"
  host: 172.22.15.132
  database: peliswatch_dev
  encoding: utf8

development:
  <<: *default
  database: peliswatch_dev

test:
  <<: *default
  database: peliswatch_test

production:
  <<: *default
  database: peliswatch_prod